### ISSUE TITLE
Whitescreen on firefox

### ISSUE THREAD

**Issue by TheBigBlockPC** [DouglasDwyer/octo-release#15]
i've tryed to run your voxel demo on firefox on linux with up to date drivers installed and i only get a whitescreen and this error:
Mutations-Ereignisse sollten nicht mehr verwendet werden. Verwenden Sie MutationObserver stattdessen. octo-release:13:53
INFO game\client\src\lib.rs:30 
Starting persistent threadpool with 1 worker(s). web-ec4ef320bf5c04c.js:1101:17
Uncaught (in promise) TypeError: getObject(...) is undefined
    __wbg_requestAdapter_9e8b0535a7f4ae87 https://douglasdwyer.github.io/octo-release/web-ec4ef320bf5c04c.js:1383
    __wbg_finalize_init https://douglasdwyer.github.io/octo-release/web-ec4ef320bf5c04c.js:1956
    __wbg_init https://douglasdwyer.github.io/octo-release/web-ec4ef320bf5c04c.js:1992
web-ec4ef320bf5c04c.js:1383:30

**Comment by DouglasDwyer** [comment]
Hey there, thanks for trying out the demo. As stated in the README, the demo is only supported in Chrome/Edge/Opera, or on native Windows. In the future, I will work on making an error message that will display that info (instead of showing a white screen). You can try a different browser if you'd like!

**Comment by TheBigBlockPC** [comment]
thanks for informing me about the supported browsers
