### ISSUE TITLE
If there is no ground beneath you, you don't fall

### ISSUE THREAD

**Issue by ookami125** [DouglasDwyer/octo-release#3]
I built up to 10,000 units (only 1400 needed) and found when I walked off the pillar I just floated there, proceeded to completely destroy the pillar and got stuck. I imagine it should work the same as when you lodge yourself in the ground and it slowly moves you up until you reach the surface.

**Comment by RedNicStone** [comment]
I think movement is a general issue right now sine your vertical position is determined by the highest voxel on your feet position.
My best guess is that in your case the "ground" chunks are onloaded so the engine is unable to locate a highest voxel and freezes you temporarily.
Since the engine is in an early stage I don't think movement needs to be refined at the moment.

**Comment by DouglasDwyer** [comment]
Thanks for pointing this out! RedNicStone is absolutely on-the-money about why this occurs. Since the chunks beneath you aren't loaded, the engine won't teleport you to the ground. I simply haven't implemented any actual physics into the game yet, which is why this problem occurs. Once I have working rigidbody collision detection, then I can refine the movement. For now, though, I'm going to close this issue. I appreciate you trying out the demo :)
