### ISSUE TITLE
Crashes on Android Phone

### ISSUE THREAD

**Issue by allain** [DouglasDwyer/octo-release#4]
Great project!

Running the demo caused my mobile chrome browser to crash after about 10 seconds.

I was able to repeat this sequence a couple times:

1. Load demo
2. Click Play on about dialog (nothing happens)
3. Voxels appear but staggered
4. Browser restarts

If you need me to try anything please let me know.

**Comment by DouglasDwyer** [comment]
Hey, thanks for checking out the demo! While the error handling/reporting could definitely be improved, it sounds like you're experiencing a context loss. When a WebGL application requests too many resources, the browser will typically reset itself. Since you're able to play but only for a short time, this is probably the case.

Currently, the goal of this project is to run well on desktop machines. Supporting mobile is not my focus, because mobile GPUs are even less powerful than desktop integrated GPUs. As such, I can't really promise to debug this - unless you have reason to believe that your phone's hardware *should* be capable of handling the demo.

Definitely, in the final version of the online game, an error screen should occur when the user attempts to play on mobile hardware. Some tablets might be powerful enough, or maybe running the game as a native app would viable, but right now I'm just trying to get desktop working :)
